### Bob creating a course
POST http://localhost:8080/courses
Content-Type: application/json
Authorization: Basic aGFtYWRhQGV4YW1wbGUuY29tOnBhc3N3b3Jk

{
  "balance": 35000
}

### Bob creating a course
GET http://localhost:8080/sec/accounts
Content-Type: application/json
Authorization: Basic aGFtYWRhQGV4YW1wbGUuY29tOnBhc3N3b3Jk



### Bob using API Key authentication
GET http://localhost:8080/sec/accounts
Api-Key: ABCDEFGHIJKLMNOPQRSTUVWX